### ISSUE TITLE
乱码出现。。。。

### ISSUE THREAD

**Issue by ihrthk** [westlinkin/AndroidLocalizationer#1]
源英文版：
 <string name="app_name">My Application</string>
    <string name="hello_world">Hello world!</string>
    <string name="action_settings">Settings</string>

现日文版：
<string name="app_name">˽�Υ��ץꥱ�`�����</string>
	<string name="hello_world">�ϥ�`��`��ɣ�</string>
	<string name="action_settings">�O��</string>

**Comment by westlinkin** [comment]
fixed in version 0.1.5
