### ISSUE TITLE
Many translations come back as ???????????

### ISSUE THREAD

**Issue by jkane001** [westlinkin/AndroidLocalizationer#17]
I have some fairly simple strings that, in some languages, are coming back as just a series of ???. 

For example, in Chinese Simplified, this string resource:
>\<string name="state_connected"\>Device connected\</string\>

comes back as:
>\<string name="state_connected"\>????\</string\>

**Comment by AbdallaEssa92** [comment]
occurred with me also

**Comment by itsalltoomuch** [comment]
Me too. How can I solve this ?

**Comment by GodLikeThomas** [comment]
Me too.Any solution??

**Comment by westlinkin** [comment]
fixed in version 0.1.5

**Comment by chinaliuweijie** [comment]
Android Localizationer threw an uncaught NullPointerException. Disable Plugin

**Comment by 2014james** [comment]
Android Localizationer threw an uncaught NullPointerException. Disable Plugin

**Comment by edy1** [comment]
It doesn't work anymore. Can you please fix it?
