### ISSUE TITLE
Not work on Android Studio 1.0.1

### ISSUE THREAD

**Issue by dizaii** [westlinkin/AndroidLocalizationer#6]
ClassCastException: com.sun.xml.internal.stream.events.EndElementEvent cannot be cast to javax.xml.stream.events.Characters: com.sun.xml.internal.stream.events.EndElementEvent cannot be cast to javax.xml.stream.events.Characters

**Comment by taimur97** [comment]
worked on mine

**Comment by westlinkin** [comment]
Please try [Version 0.1.3](https://github.com/westlinkin/AndroidLocalizationer/raw/master/AndroidLocalizationer.zip), and see if it is fixed.

**Comment by westlinkin** [comment]
No more updates from @dizaii , close.
